#!/usr/bin/env php
<?php

require_once('init.php');

try {
    $class      = ucfirst($argv[1]);
    $method     = $argv[2];
    $obj        = __CLI__ . $class;
    $class      = new $obj();
    $value      = null;
    if (!empty($argv[3])) {
        parse_str($argv[3],$value);
    }
    $class->{$method}($value);
} catch (\Exception $e) {
  echo $e->getMessage();
}
